name: pwm
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.8.30=hbcca054_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgomp=14.1.0=h77fa898_1
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.46.1=hadc24fc_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=h4ab18f5_1
  - ncurses=6.5=he02047a_1
  - openssl=3.3.2=hb9d3cd8_0
  - pip=24.2=pyh8b19718_1
  - python=3.10.14=hd12c33a_0_cpython
  - readline=8.2=h8228510_1
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.44.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
    - accelerate==0.21.0
    - affine==2.4.0
    - aioboto3==14.1.0
    - aiobotocore==2.21.1
    - aiofiles==24.1.0
    - aiohttp==3.9.5
    - aioitertools==0.12.0
    - aiosignal==1.3.1
    - albumentations==0.3.2
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - anykeystore==0.2
    - asn1crypto==1.5.1
    - asttokens==2.4.1
    - async-timeout==4.0.3
    - attrs==25.3.0
    - bidict==0.23.1
    - blessed==1.20.0
    - bokeh==2.4.3
    - boto3==1.37.1
    - botocore==1.37.1
    - braceexpand==0.1.7
    - cachetools==5.3.3
    - casadi==3.7.0
    - certifi==2024.2.2
    - cffi==1.16.0
    - chardet==5.2.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - click-plugins==1.1.1
    - cligj==0.7.2
    - clip==0.2.0
    - clip-openai==1.0.post20230121
    - cmake==3.29.3
    - control==0.9.1
    - cramjam==2.8.3
    - crcmod==1.7
    - cryptacular==1.6.2
    - cryptography==39.0.2
    - cycler==0.12.1
    - datasets==3.2.0
    - decorator==4.4.2
    - decord==0.6.0
    - deepspeed==0.14.2
    - defusedxml==0.7.1
    - deprecated==1.2.14
    - descartes==1.1.0
    - diffusers==0.30.1
    - dill==0.3.8
    - distlib==0.3.8
    - distro-info==1.0
    - dnspython==2.6.1
    - docker-pycreds==0.4.0
    - docstring-parser==0.16
    - ecdsa==0.19.0
    - einops==0.6.0
    - exceptiongroup==1.2.1
    - executing==2.0.1
    - fairscale==0.4.13
    - fastparquet==2024.5.0
    - ffmpegcv==0.3.13
    - filelock==3.14.0
    - fiona==1.10.1
    - fire==0.6.0
    - fonttools==4.51.0
    - frozenlist==1.4.1
    - fsspec==2023.6.0
    - ftfy==6.2.0
    - geopandas==1.0.1
    - gitdb==4.0.11
    - gitpython==3.1.43
    - gpustat==1.1.1
    - greenlet==3.0.3
    - grpcio==1.64.0
    - guppy3==3.1.2
    - h11==0.14.0
    - hjson==3.1.0
    - huggingface-hub==0.23.2
    - hupper==1.12.1
    - hydra-core==1.2.0
    - idna==3.7
    - imageio==2.34.1
    - imageio-ffmpeg==0.5.1
    - imgaug==0.2.6
    - importlib-metadata==8.5.0
    - iniconfig==2.0.0
    - ipaddress==1.0.23
    - ipdb==0.13.13
    - ipython==8.18.1
    - jaxtyping==0.2.28
    - jedi==0.19.1
    - jinja2==3.1.4
    - jmespath==1.0.1
    - joblib==1.4.2
    - jsonargparse==4.14.1
    - jsonlines==4.0.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - kiwisolver==1.4.5
    - kornia==0.7.2
    - kornia-rs==0.1.3
    - lazy-loader==0.4
    - lightning==2.2.3
    - lightning-utilities==0.11.2
    - lit==18.1.6
    - lpips==0.1.4
    - markupsafe==2.1.5
    - matplotlib==3.5.3
    - matplotlib-inline==0.1.7
    - miscreant==0.3.0
    - moviepy==1.0.3
    - mpmath==1.3.0
    - msgpack==1.0.8
    - multidict==6.0.5
    - multiprocess==0.70.16
    - natsort==8.4.0
    - nest-asyncio==1.6.0
    - networkx==3.2.1
    - ninja==1.11.1.1
    - numpy==1.23.4
    - nuscenes-devkit==1.1.11
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-ml-py==12.560.30
    - nvidia-nccl-cu12==2.19.3
    - nvidia-nvjitlink-cu12==12.6.68
    - nvidia-nvtx-cu12==12.1.105
    - oauthlib==3.2.2
    - omegaconf==2.3.0
    - open-clip-torch==2.24.0
    - openai-clip==1.0.1
    - opencv-python==4.9.0.80
    - opencv-python-headless==3.4.18.65
    - outcome==1.3.0.post0
    - packaging==22.0
    - pandas==1.5.3
    - parquet==1.3.1
    - parso==0.8.4
    - pastedeploy==3.1.0
    - pathlib2==2.3.7.post1
    - pathtools==0.1.2
    - pbkdf2==1.3
    - peft==0.13.1
    - pexpect==4.9.0
    - pillow==10.3.0
    - piqa==1.3.2
    - plaster==1.1.2
    - plaster-pastedeploy==1.0.1
    - platformdirs==4.2.2
    - plotly==5.22.0
    - pluggy==1.5.0
    - ply==3.11
    - proglog==0.1.10
    - promise==2.3
    - prompt-toolkit==3.0.43
    - protobuf==3.20.3
    - psutil==5.9.8
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py==1.11.0
    - py-cpuinfo==9.0.0
    - py-spy==0.3.14
    - pyarrow==19.0.0
    - pyarrow-hotfix==0.6
    - pyasn1==0.6.0
    - pycocoevalcap==1.2
    - pycocotools==2.0.7
    - pycparser==2.22
    - pycryptodomex==3.20.0
    - pycurl==7.43.0.6
    - pydantic==1.10.15
    - pydantic-core==2.18.3
    - pygments==2.18.0
    - pyinstrument==5.0.1
    - pyjwt==2.8.0
    - pynvml==11.5.0
    - pyogrio==0.10.0
    - pyope==0.2.2
    - pyopenssl==23.2.0
    - pyparsing==3.1.2
    - pyproj==3.7.1
    - pyquaternion==0.9.9
    - pyramid==2.0.2
    - pyramid-mailer==0.15.1
    - pysocks==1.7.1
    - pytest==6.2.5
    - python-consul==1.1.0
    - python-dateutil==2.9.0.post0
    - python-engineio==4.9.1
    - python-etcd==0.4.5
    - python-jose==3.3.0
    - python-socketio==5.11.2
    - python3-openid==3.2.0
    - pytorch-extension==0.2
    - pytorch-lightning==2.2.3
    - pytz==2024.1
    - pyyaml==6.0.1
    - rasterio==1.3.11
    - ray==2.44.1
    - referencing==0.36.2
    - regex==2024.5.15
    - repoze-sendmail==4.4.1
    - requests==2.32.3
    - requests-oauthlib==2.0.0
    - responses==0.18.0
    - retry==0.9.2
    - rpds-py==0.24.0
    - rsa==4.9
    - rtree==1.4.0
    - s3transfer==0.11.3
    - safetensors==0.4.3
    - schedule==1.2.2
    - scikit-image==0.22.0
    - scikit-learn==1.5.0
    - scipy==1.13.1
    - selenium==4.30.0
    - sentencepiece==0.2.0
    - sentry-sdk==2.3.1
    - setproctitle==1.3.3
    - setuptools==75.1.0
    - shapely==2.0.7
    - shortuuid==1.0.13
    - simple-websocket==1.0.0
    - six==1.16.0
    - smmap==5.0.1
    - sniffio==1.3.1
    - snuggs==1.4.7
    - sortedcontainers==2.4.0
    - sqlalchemy==1.4.27
    - stack-data==0.6.3
    - sympy==1.12
    - taming-transformers-rom1504==0.0.6
    - tenacity==8.3.0
    - tensorboardx==2.6.2.2
    - termcolor==2.4.0
    - threadpoolctl==3.5.0
    - thriftpy2==0.5.0
    - tifffile==2024.5.22
    - timm==1.0.3
    - tokenizers==0.19.1
    - toml==0.10.2
    - tomli==2.0.1
    - torch==2.2.1
    - torch-fidelity==0.3.0
    - torchmetrics==1.4.0.post0
    - torchvision==0.17.1
    - tornado==6.4.2
    - tox==3.28.0
    - tqdm==4.66.4
    - traitlets==5.14.3
    - transaction==4.0
    - transformers==4.41.1
    - translationstring==1.4
    - trio==0.29.0
    - trio-websocket==0.12.2
    - triton==2.2.0
    - typeguard==2.13.3
    - typing-extensions==4.12.0
    - tzdata==2024.1
    - urllib3==1.26.18
    - velruse==1.1.1
    - venusian==3.1.0
    - virtualenv==20.26.2
    - wandb==0.17.0
    - watchdog==4.0.1
    - wcwidth==0.2.13
    - webdataset==0.2.86
    - webob==1.8.7
    - websocket-client==1.8.0
    - wrapt==1.16.0
    - wsproto==1.2.0
    - wtforms==3.1.2
    - wtforms-recaptcha==0.3.2
    - xformers==0.0.25
    - xxhash==3.4.1
    - yarl==1.9.4
    - zipp==3.20.2
    - zope-deprecation==5.0
    - zope-interface==6.4.post2
    - zope-sqlalchemy==3.1
